apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: xiaozhoucui/kub-data-demo
          imagePullPolicy: Always
          env:
            - name: STORY_FOLDER
              # value: "story" # story is hardecoded
              valueFrom: # use value from environment.yaml 
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          volumeMounts:
            - mountPath: /app/story # path of the text file in container
              name: story-volume
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          # ports:
          # - containerPort: <Port>
      volumes:
        - name: story-volume
          # emptyDir: {} # volume type
          # hostPath: # volume type
          #   path: /data # like Bind Mounts in docker
          #   type: DirectoryOrCreate
          persistentVolumeClaim:
            claimName: host-pvc
