apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector: # pods
    app: frontend
  type: LoadBalancer # LoadBalancer allows outside world access. Other types are ClusterIP and NodePort
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
