apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector: # pods
    app: users
  type: LoadBalancer # LoadBalancer allows outside world access. Other types are ClusterIP and NodePort
  ports:
    - protocol: "TCP"
      port: 8080 # incoming requests to the LoadBalancer
      targetPort: 8080 # from node app
