apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: xiaozhoucui/kub-demo-users:latest
          env:
            - name: AUTH_ADDRESS
              # value: "10.107.88.2"
              value: "auth-service.default" # CoreDNS domain: [k8s service name].[k8s namespace]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
