version: "3.8"

services:
  server:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes: # pass config file into container
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    # nginx.conf talk to 3000 externally; php image expose 9000 internally
    ports:
      - "3000:9000"
    # alternatively, remove ports and change nginx.conf to "fastcgi_pass php:9000"
  # mysql:
  # composer:
  # artisan:
  # npm:
