version: "3.8"

services:
  server:
    image: "nginx:stable-alpine"
    # build: 
    #   # set to the yaml file's folder, because subfolders "src" and "nginx" will be copied
    #   context: .
    #   dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      # "." becaulse src subfolder will be copied
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    # nginx.conf talk to 3000 externally; php image expose 9000 internally
    # ports:
    #   - "3000:9000"
    # alternatively, remove ports and change nginx.conf to "fastcgi_pass php:9000"
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes: 
      - ./src:/var/www/html
