apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: example
spec:
  selector: # choose which pods will be part of this service
    app: second-app # label of pods
  ports: # ports to be exposed
    - protocol: "TCP"
      port: 80 # external port
      targetPort: 8080 # container internal port, app.js listener
    # - protocol: "TCP"
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer # can also be "ClusterIP" or "NodeIP"